version: "2"

services:
  sonarqube:
    image: sonarqube
    ports:
        - "9000:9000"
    networks:
      - sonarnet
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    networks:
      - sonarnet

networks:
  sonarnet:
    driver: bridge
